# SQL_view.py
wanted data view: '*'
table view: [hp_20211224_RAM]

# Input.py
file input: '12_23_17_33_results.txt'
Key ID: '3'
Client Name: 'hp'
Date: '20211224' #format example:20210101
Disk Type: 'RAM'

# SQL_select.py
wanted data: '*'
table: [hp_20211224_RAM]
statement: 'Number_of_Job = "64" AND IOdepth = "256"'

# SQL_select_two_table.py
wanted data1: '*'
table1: 'Guangzhou_20210924_RAM'
statement1: 'Readwrite_type = "read" AND Number_of_Job = "8" AND IOdepth = "8"'
wanted data2: '*'
table2: 'Taiwan_20210922_SDD'
statement2: 'Readwrite_type = "read" AND Number_of_Job = "8" AND IOdepth = "8"'

# SQL_chart.py
Select_Data: 'IOPS' # IOPS / MBPS 
Table_Names: 'hp_20211224_RAM'
ReadWrite_Type: '"randwrite"' # read, write, randread, randwrite
Number_of_Job: '"64"'
IOdepth: '"256"'

# chart_readwrite.py
Select_Data_rw: 'IOPS' # IOPS / MBPS 
Table_Names_rw: 'hp_20211224_RAM'
Number_of_Job_rw: '"64"'
IOdepth_rw: '"256"'

# SQL_histogram.py
Select_Data_hist: 'IOPS' # IOPS / MBPS 
Table_hist: [hp_20211224_RAM]
Readwrite_hist: '"randwrite"' # read, write, randread, ranwrite
Number_of_Job_hist: '"64"' 
IOdepth_hist: '"256"'
Blocksize_hist: '"4k"' # 4k / 1M

# SQL_deviation.py
Standard_Value: IOPS # IOPS / MBPS
Table_Name_devi_1: 'hp_20211224_RAM'
ReadWrite_Type_Stan: '"randread"' # # read, write, randread, ranwrite

Example_Value: IOPS # IOPS / MBPS
Table_Name_devi_2: 'hp_20211224_RAM'
ReadWrite_Type_Ex: '"randwrite"' # # read, write, randread, ranwrite

# SQL_deviation_1standard.py
Standard_Value_1: IOPS # IOPS / MBPS
Table_Name_devi_Stan: 'VersaPLX2000_20211220_RAM_sdb_sdc'
ReadWrite_Type_1Stan: '"randwrite"' # # read, write, randread, ranwrite
Blocksize_Stan: '"4k"'

Example_Value_2: IOPS # IOPS / MBPS
Table_Name_devi_Ex: 'VersaPLX2000_20211220_RAM_sdb_sdc'
ReadWrite_Type_1Ex: '"randwrite"' # # read, write, randread, ranwrite