# SQL_view.py
wanted data view: '*'
table view: [hp_20211224_RAM, hp_20211230_RAM]

# Input.py
file input: '12_29_07_52_results.txt'
Key ID: '6'
Client Name: 'VersaPLX2000'
Date: '20211230' #format example:20210101
Disk Type: 'drbd'

# SQL_select.py
wanted data: '*'
table: [VersaPLX2000_20211230_drbd, VersaPLX2000_20211229_Container]
statement: 'Number_of_Job = "8" AND IOdepth = "8"'

# SQL_select_two_table.py
wanted data1: '*'
table1: 'VersaPLX2000_20211229_Container'
statement1: 'Number_of_Job = "8" AND IOdepth = "8"'
wanted data2: '*'
table2: 'VersaPLX2000_20211230_drbd'
statement2: 'Number_of_Job = "8" AND IOdepth = "8"'

# SQL_chart.py
Select_Data: 'IOPS' # IOPS / MBPS 
Table_Names: 'VersaPLX2000_20211230_drbd'
ReadWrite_Type: '"randwrite"' # read, write, randread, randwrite
Number_of_Job: '"8"'
IOdepth: '"8"'

# chart_readwrite.py
Select_Data_rw: 'IOPS' # IOPS / MBPS 
Table_Names_rw: 'VersaPLX2000_20211230_drbd'
Number_of_Job_rw: '"8"'
IOdepth_rw: '"8"'

# SQL_histogram.py
Select_Data_hist: 'IOPS' # IOPS / MBPS 
Table_hist: [VersaPLX2000_20211230_drbd,VersaPLX2000_20211229_Container]
Readwrite_hist: '"randwrite"' # read, write, randread, ranwrite
Number_of_Job_hist: '"8"' 
IOdepth_hist: '"8"'
Blocksize_hist: '"1m"' # 4k / 1M

# SQL_deviation.py
Standard_Value: IOPS # IOPS / MBPS
Table_Name_devi_1: 'VersaPLX2000_20211230_drbd'
ReadWrite_Type_Stan: '"randwrite"' # # read, write, randread, ranwrite
Blocksize_Stan: '"4k"' # used for one standard

Example_Value: IOPS # IOPS / MBPS
Table_Name_devi_2: 'VersaPLX2000_20211229_Container'
ReadWrite_Type_Ex: '"randwrite"' # # read, write, randread, ranwrite